compile:
	@echo "Compiling program file...\n"
	@gcc -o mytee tee.c
	@echo "Compilation done.\n"
	@echo "USAGE:\n"
	@echo "./mytee -> just writes input from stdin to stdout\n"
	@echo "./mytee file1.txt file2.txt -> writes input from stdin to stdout and the files\n"
	@echo "ping google.com | ./mytee file1.txt -> usage with pipes\n"
