compile:
	@echo "Compiling program...\n"
	@gcc -o vote voting.c
	@echo "Program compiled!\n"
	@echo "\nUSAGE:\n"
	@echo "./vote {child count} \n// default value of child count will be 5"
	@echo "Example: ./vote 4"
